export enum CategoriaEnum {
  LENTES_DE_SOL = 'LENTES_DE_SOL',
  LENTES_DE_CONTACTO = 'LENTES_DE_CONTACTO',
  FOTOGRAFIA = 'FOTOGRAFIA',
  AUDIOLOGIA = 'AUDIOLOGIA',
  LENTES_AEREOS = 'LENTES_AEREOS',
  CRISTALES = 'CRISTALES',
  OTROS = 'OTROS',
}
