export enum CategoriaEnum {
  LENTESDESOL = 'LENTESDESOL',
  LENTESDECONTACTO = 'LENTESDECONTACTO',
  HANDBAGS = 'HANDBAGS',
  LENTESAEREOS = 'LENTESAEREOS',
  CRISTALES = 'CRISTALES',
  OTROS = 'OTROS',
}
