export enum CategoriaEnum {
  LENTES_DE_SOL = 'LENTES DE SOL',
  LENTES_DE_CONTACTO = 'LENTES DE CONTACTO',
  FOTOGRAFIA = 'FOTOGRAFIA',
  AUDIOLOGIA = 'AUDIOLOGIA',
  LENTES_AEREOS = 'LENTES AEREOS',
  CRISTALES = 'CRISTALES',
  OTROS = 'OTROS',
}
